// Code generated by protoc-gen-go. DO NOT EDIT.
// source: features.proto

package grpcapi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GrpcFeaturesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrpcFeaturesRequest) Reset()         { *m = GrpcFeaturesRequest{} }
func (m *GrpcFeaturesRequest) String() string { return proto.CompactTextString(m) }
func (*GrpcFeaturesRequest) ProtoMessage()    {}
func (*GrpcFeaturesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216f05915163cdf, []int{0}
}

func (m *GrpcFeaturesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcFeaturesRequest.Unmarshal(m, b)
}
func (m *GrpcFeaturesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcFeaturesRequest.Marshal(b, m, deterministic)
}
func (m *GrpcFeaturesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcFeaturesRequest.Merge(m, src)
}
func (m *GrpcFeaturesRequest) XXX_Size() int {
	return xxx_messageInfo_GrpcFeaturesRequest.Size(m)
}
func (m *GrpcFeaturesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcFeaturesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcFeaturesRequest proto.InternalMessageInfo

type GrpcFeaturesResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	IsActive             bool     `protobuf:"varint,3,opt,name=isActive,proto3" json:"isActive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrpcFeaturesResponse) Reset()         { *m = GrpcFeaturesResponse{} }
func (m *GrpcFeaturesResponse) String() string { return proto.CompactTextString(m) }
func (*GrpcFeaturesResponse) ProtoMessage()    {}
func (*GrpcFeaturesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216f05915163cdf, []int{1}
}

func (m *GrpcFeaturesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcFeaturesResponse.Unmarshal(m, b)
}
func (m *GrpcFeaturesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcFeaturesResponse.Marshal(b, m, deterministic)
}
func (m *GrpcFeaturesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcFeaturesResponse.Merge(m, src)
}
func (m *GrpcFeaturesResponse) XXX_Size() int {
	return xxx_messageInfo_GrpcFeaturesResponse.Size(m)
}
func (m *GrpcFeaturesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcFeaturesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcFeaturesResponse proto.InternalMessageInfo

func (m *GrpcFeaturesResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GrpcFeaturesResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GrpcFeaturesResponse) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func init() {
	proto.RegisterType((*GrpcFeaturesRequest)(nil), "grpcapi.GrpcFeaturesRequest")
	proto.RegisterType((*GrpcFeaturesResponse)(nil), "grpcapi.GrpcFeaturesResponse")
}

func init() { proto.RegisterFile("features.proto", fileDescriptor_2216f05915163cdf) }

var fileDescriptor_2216f05915163cdf = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x4b, 0x4d, 0x2c,
	0x29, 0x2d, 0x4a, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0x2f, 0x2a, 0x48,
	0x4e, 0x2c, 0xc8, 0x54, 0x12, 0xe5, 0x12, 0x76, 0x2f, 0x2a, 0x48, 0x76, 0x83, 0x4a, 0x07, 0xa5,
	0x16, 0x96, 0xa6, 0x16, 0x97, 0x28, 0xa5, 0x71, 0x89, 0xa0, 0x0a, 0x17, 0x17, 0xe4, 0xe7, 0x15,
	0xa7, 0x0a, 0x09, 0x70, 0x31, 0x67, 0xa7, 0x56, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81,
	0x98, 0x42, 0x0a, 0x5c, 0xdc, 0x29, 0xa9, 0xc5, 0xc9, 0x45, 0x99, 0x05, 0x25, 0x99, 0xf9, 0x79,
	0x12, 0x4c, 0x60, 0x19, 0x64, 0x21, 0x21, 0x29, 0x2e, 0x8e, 0xcc, 0x62, 0xc7, 0xe4, 0x92, 0xcc,
	0xb2, 0x54, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0x38, 0xdf, 0x28, 0x8a, 0x8b, 0x03, 0x66,
	0x87, 0x90, 0x1f, 0x17, 0xb7, 0x7b, 0x6a, 0x09, 0x9c, 0x2b, 0xa3, 0x07, 0x75, 0xa3, 0x1e, 0x16,
	0x07, 0x4a, 0xc9, 0xe2, 0x90, 0x85, 0xb8, 0x53, 0x89, 0xc1, 0x80, 0x31, 0x89, 0x0d, 0xec, 0x55,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x48, 0xb5, 0x1e, 0xfc, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FeaturesClient is the client API for Features service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FeaturesClient interface {
	GetFeatures(ctx context.Context, in *GrpcFeaturesRequest, opts ...grpc.CallOption) (Features_GetFeaturesClient, error)
}

type featuresClient struct {
	cc *grpc.ClientConn
}

func NewFeaturesClient(cc *grpc.ClientConn) FeaturesClient {
	return &featuresClient{cc}
}

func (c *featuresClient) GetFeatures(ctx context.Context, in *GrpcFeaturesRequest, opts ...grpc.CallOption) (Features_GetFeaturesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Features_serviceDesc.Streams[0], "/grpcapi.Features/GetFeatures", opts...)
	if err != nil {
		return nil, err
	}
	x := &featuresGetFeaturesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Features_GetFeaturesClient interface {
	Recv() (*GrpcFeaturesResponse, error)
	grpc.ClientStream
}

type featuresGetFeaturesClient struct {
	grpc.ClientStream
}

func (x *featuresGetFeaturesClient) Recv() (*GrpcFeaturesResponse, error) {
	m := new(GrpcFeaturesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FeaturesServer is the server API for Features service.
type FeaturesServer interface {
	GetFeatures(*GrpcFeaturesRequest, Features_GetFeaturesServer) error
}

// UnimplementedFeaturesServer can be embedded to have forward compatible implementations.
type UnimplementedFeaturesServer struct {
}

func (*UnimplementedFeaturesServer) GetFeatures(req *GrpcFeaturesRequest, srv Features_GetFeaturesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetFeatures not implemented")
}

func RegisterFeaturesServer(s *grpc.Server, srv FeaturesServer) {
	s.RegisterService(&_Features_serviceDesc, srv)
}

func _Features_GetFeatures_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GrpcFeaturesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FeaturesServer).GetFeatures(m, &featuresGetFeaturesServer{stream})
}

type Features_GetFeaturesServer interface {
	Send(*GrpcFeaturesResponse) error
	grpc.ServerStream
}

type featuresGetFeaturesServer struct {
	grpc.ServerStream
}

func (x *featuresGetFeaturesServer) Send(m *GrpcFeaturesResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Features_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.Features",
	HandlerType: (*FeaturesServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetFeatures",
			Handler:       _Features_GetFeatures_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "features.proto",
}
